- hosts: AppInstance
  become: yes
  tasks:
    - name: Atualizar todos os pacotes do sistema
      apt:
        upgrade: yes
        update_cache: yes

    - name: Instalar Docker e Docker Compose
      apt:
        name: ['docker', 'docker-compose']
        state: present

    - name: Copiar código da aplicação e arquivos Docker
      copy:
        src: /path/to/your/app
        dest: /path/to/destination

    - name: Iniciar a aplicação com Docker Compose
      command: docker-compose up -d